export enum Role {
    ADMIN = "ADMIN",
    TEACHER = "TEACHER",
    STUDENT = "STUDENT",
}

export enum TEACHER_TYPE {
    TEACHER = "TEACHER",
    ASSISTANT_TEACHER = "ASSISTANT TEACHER",
    GUEST_TEACHER = "GUEST TEACHER",
}